name: Build and Test

on:
  push:
  pull_request:
jobs:
  win-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install tools
      run: dotnet tool restore
    - name: Install OpenCL Runtime
      run: choco install opencl-intel-cpu-runtime
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
          CI: true
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
          CI: true
    - name: CheckDevices
      run: dotnet run --project src/CheckDevices
      env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
          CI: true
